[package]
name = "subjectid"
version = "0.1.0"
edition = "2021"
description = "Implementation of Subject Identifiers for Security Event Tokens"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
