name: Deploy Docs to Github Pages
on:
  workflow_dispatch: # to run manually
  push:
    branches:
      - main

jobs:
  # Astro build job
  build:
    runs-on: ubuntu-latest
    steps:
      # astro configuration defined in `setup-docs`
      - name: Checkout docs setup
        uses: actions/checkout@v4
        with:
          ref: setup-docs
      # markdown content in `main` branch, perform multi checkout
      - name: Checkout doc content
        uses: actions/checkout@v4
        with:
          ref: main
          sparse-checkout: |
            design
          path: branch-main
      # move required markdown content to docs directory
      - name: Move doc content
        run: mv branch-main/design src/content/docs
      # build with astro
      - name: Astro build
        uses: withastro/action@v0
        with:
          node-version: 20
          pnpm-version: 8.x.x

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2